const express=require('express')
const router=express.Router()
const authAdmin=require('../middlware/authAdmin')
const controller=require('../controller/product')

router.post('/product',authAdmin,controller.createProduct)
router.put('/product/:id',authAdmin,controller.updateProduct)
router.get('/product/:id',authAdmin,controller.getOneProduct)
router.get('/productCategory/:id',authAdmin,controller.getProductsCategory)
router.get('/allProducts',authAdmin,controller.getAllProducts)